### PR TITLE
Fix header component - Closes #506

### LINKED ISSUE #506: Fix Header component
### Expected behaviour
- Only logo is displayed if user not logged in.
- Logout button works.
- Bigger margin-bottom and smaller margin-right (align open drop-down menu)

### PR DESCRIPTION
**Pull request by alepop**
- Add `<PrivateWrapper />` component
- Handle logout action on Logout button click
- Align drop-down menu
close #506

### CODE REVIEW

File: src/components/privateWrapper/index.js [hunk 1]
```diff
@@ -0,0 +1,12 @@
+import React from 'react';
+import { connect } from 'react-redux';
+
+export const PrivateWrapperComponent = ({ isAuthenticated, children }) => (
+    isAuthenticated && <span>{ children }</ span>
+);
+
+const mapStateToProps = state => ({
+  isAuthenticated: !!state.account.publicKey,
```
Comment (slaweet) [inline src/components/privateWrapper/index.js]: this should be something else then `publicKey` because now it shows the haeder right when I click the "Login" button, but it should only after the server request is finished and it is redirected from login page.

File: src/components/transactions/transactionsComponent.js [hunk 2]
```diff
@@ -39,7 +39,7 @@ class Transactions extends React.Component {
           length: parseInt(res.count, 10),
         });
       })
-      .catch(error => console.error(error.message));
+      .catch(error => console.error(error.message)); //eslint-disable-line
```
Comment (slaweet) [inline src/components/transactions/transactionsComponent.js]: I see that finally somebody got annoyed enough by the warning in console :-) Though I would prefer to disable the specific rule. In this case a believe it is `//eslint-disable-line no-console`

File: src/components/header/header.css [hunk 3]
```diff
@@ -16,3 +16,7 @@
 .material-icons{
     font-size: 24px !important;
 }
+
+.menu {
+    right: -16px !important;
```
Comment (slaweet) [inline src/components/header/header.css]: This could be less (maybe `right: -8px !important;`) and the put the rest on `.wrapper`.
`.wrapper` has too much space on the right compared to nano 1.0.0 and not enough at the bottom. 

I mean something like this is missing
```
.wrapper {
  margin-right: -8px;
  margin-bottom: 16px;
}
```

File: src/components/privateWrapper/index.js (hunk 1 above)
Comment (alepop) [inline src/components/privateWrapper/index.js]: currently, all private routes look to the same params.

File: src/components/header/header.css (hunk 3 above)
Comment (alepop) [inline src/components/header/header.css]: `menu` is a theme param, and it passes to the component and merges with other styles. it is so hard to style `Menu` component through `IconMenu` component.

File: src/components/privateWrapper/index.js (hunk 1 above)
Comment (slaweet) [inline src/components/privateWrapper/index.js]: In private routes, it makes no user-visible difference. But on the login page if user is on slower network, it can longer time for the request and only then user is redirected from login page. These login buttons should not be on login page.

File: src/components/header/header.css (hunk 3 above)
Comment (slaweet) [inline src/components/header/header.css]: I mean `.wrapper` which is defined and used in our `header` component. Nothing extra in `IconMenu`
https://github.com/alepop/lisk-nano/blob/2c484cfd1565634b4f682fbf207ee2bc3ce3bb42/src/components/header/header.css#L1-L4
https://github.com/alepop/lisk-nano/blob/2c484cfd1565634b4f682fbf207ee2bc3ce3bb42/src/components/header/headerElement.js#L12-L13

File: src/components/privateWrapper/index.js (hunk 1 above)
Comment (slaweet) [inline src/components/privateWrapper/index.js]: This was fixed in the meantime by some other changes.

File: src/components/header/header.css (hunk 3 above)
Comment (slaweet) [inline src/components/header/header.css]: This is still an issue

Comment (alepop) [inline src/components/header/header.css]: Do i need to fix it in other pr?

Comment (slaweet) [inline src/components/header/header.css]: Yes, please.
