### PR TITLE
ConfirmVotes component should check validity of second passphrase - Closes #628

### LINKED ISSUE #628: ConfirmVotes component should check validity of second passphrase before firing the action
### Expected behaviour
As title suggests, ConfirmVotes component should use `passphrase` utility to validate secondPasspharase before firing `votePlaced` action.

### Actual behaviour
no validation is implemented yet

### Steps to reproduce
Try voting with a structurally wrong second passphrase. The app will call Api.

### PR DESCRIPTION
**Pull request by yasharAyari**
Closes [#628](https://github.com/LiskHQ/lisk-nano/issues/628)

### CODE REVIEW

File: src/components/secondPassphraseInput/secondPassphraseInput.js [hunk 1]
```diff
@@ -5,21 +5,18 @@ import { isValidPassphrase } from '../../utils/passphrase';
 class SecondPassphraseInput extends React.Component {
   componentDidMount() {
     if (this.props.hasSecondPassphrase) {
-      this.props.onError(undefined, '');
+      this.props.onChange('');
```
Comment (slaweet) [inline src/components/secondPassphraseInput/secondPassphraseInput.js]: This should be `this.props.onChange('', '');`, so that in Send dialog it doesn't show the field in red from the beginning.
