### PR TITLE
Restrict initial window size on big screens - Closes #221

### LINKED ISSUE #221: Default window size is massive on large display
### Expected behaviour

On small / normal size display the current defaults make sense, and look fine.

Opening the application on a large display e.g. iMac, the default window size should constrained to approx. half or quarter of the display. Dependent on resolution available.

### Actual behaviour

I have included a Spotify window at 25% of screen estate. If I resize the application window and close, upon reopening this default comes back the same.

image

### Steps to reproduce

Open the `Lisk Nano` electron application on a high resolution / retina display, e.g. `iMac`.

### PR DESCRIPTION
**Pull request by slaweet**
To 0.5 of width and 0.7 of height.

Closes #221

### CODE REVIEW

File: app/main.js [hunk 1]
```diff
@@ -9,8 +9,8 @@ let win;
 function createWindow() {
   const { width, height } = electron.screen.getPrimaryDisplay().workAreaSize;
   win = new BrowserWindow({
-    width: width - 250,
-    height: height - 150,
+    width: width > 2000 ? Math.floor(width * 0.5) : width - 250),
+    height: height > 1000 ? Math.floor(height * 0.7) : height - 150),
```
Comment (karmacoma) [inline app/main.js]: Check parentheses.

Comment (slaweet) [inline app/main.js]: Thanks. Stupid mistake. But made me realise that this file wasn't under eslint.
