### PR TITLE
Delegate list gets slow when loading ~1000 delegates - Closes #260

### LINKED ISSUE #260: Delegate list gets slow when loading ~1000 delegates
### Expected behaviour
The voting UI should be always smooth.
### Actual behaviour
The voting UI is lagging if many delegates are displayed.
### Steps to reproduce
- Open Lisk Nano
- Log in to an account on mainnet
- Go to "Voting" tab
- Scroll down like crazy till all delegates are loaded
- Attempt to select some of them

### PR DESCRIPTION
**Pull request by slaweet**
Closes #260

### CODE REVIEW

File: src/components/voting/votingRow.js [hunk 1]
```diff
@@ -12,9 +12,15 @@ const setRowClass = ({ pending, selected, voted }) => {
   return voted ? styles.downVoteRow : '';
 };
 
-const VotingRow = (props) => {
-  const { data } = props;
-  return (<TableRow {...props} className={`${styles.row} ${setRowClass(data)}`}>
+class VotingRow extends React.Component {
+  shouldComponentUpdate(nextProps) {
```
Comment (yasharAyari) [inline src/components/voting/votingRow.js]: This line cause an eslint error.
